### PR TITLE
Cleaned up LoginView

### PR DESCRIPTION
**Pull request by myawesomehub**
Worked on LoginView and cleaned up the view. Created data model and sub-components.

### CODE REVIEW

**Comment by evelyneee** [comment]
Thanks for the contribution! I'll take a look at this tonight. At a first glance, I would say the Strings in the view model should probably be Optionals?

**Comment by myawesomehub** [comment]
> 

Are you talking about these?
 @Published var state: LoginState = .initial
    @Published var captcha: Bool = false
    @Published var captchaVCKey: String?
    @Published var captchaPayload: String?
    @Published var ticket: String? = nil
    @Published var loginError: Error? = nil

**Comment by evelyneee** [comment]
Never mind actually, it all looks good, I just read a bit too quick 🥴. I'll do a more thorough check soon but it all sounds good!

**Comment by evelyneee** [comment]
Another thing, instead of putting views in Group {}, could you use `@ViewBuilder` on the variables? Seems like better practice

**Comment by myawesomehub** [comment]
> Never mind actually, it all looks good, I just read a bit too quick 🥴. I'll do a more thorough check soon but it all sounds good!

No, problem. I can understand 😄

**Comment by myawesomehub** [comment]
> Another thing, instead of putting views in Group {}, could you use `@ViewBuilder` on the variables? Seems like better practice

Sure, will do it tomorrow.

**Comment by myawesomehub** [comment]
@evelyneee updated groups to viewbuilder 💯

**Comment by evelyneee** [comment]
Thanks! Merging

**Pull request merged**
